name: Secret Value Test

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: dev
          - env: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: generate-secret-name
        id: generate-secret-name
        run: |
          env=${{ matrix.env }}
          echo "secret_name=MY_SECRETS_${env^^}" >> $GITHUB_OUTPUT

      - name: Test secret value
        run: |
          # Get the secret value from the matrix
          SECRET="${{ secrets[steps['generate-secret-name'].outputs.secret_name] }}"

          # Check the value
          if [ "$SECRET" = "dev" ]; then
            echo "1"
            echo "heh"
          elif [ "$SECRET" = "prod" ]; then
            echo "2"
            echo "no"
            echo "nope"
          else
            echo "Unknown secret value"
          fi
